export const people = [
    {
        name: 'Václav Procházka',
        likes: '506',
        reviews: '25',
        moto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,',
        src: '/assets/portraits/business/11.webp',
        alt: 'person1',
        tel: '+420777111222', 
    },
    {
        name: 'Ondřej Efenberk',
        likes: '340',
        reviews: '20',
        moto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,',
        src: '/assets/portraits/business/17.webp',
        alt: 'person2',
        tel: '+420777111222', 
    },
    {
        name: 'Michaela Marková',
        likes: '400',
        reviews: '30',
        moto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,',
        src: '/assets/portraits/business/8.webp',
        alt: 'person2',
        tel: '+420777111222', 
    },
    {
        name: "Tereza Marková",
        likes: '200',
        reviews: '20',
        moto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,',
        src: '/assets/portraits/business/6.webp',
        alt: 'person3',
        tel: '+420777111222', 
    },
    {
        name: "Tereza Posnerová",
        likes: '158',
        reviews: '18',
        moto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,',
        src: '/assets/portraits/business/12.webp',
        alt: 'person4',
        tel: '+420777111222', 
    },
    {
        name: "Lukáš Matouš",
        likes: '158',
        reviews: '18',
        moto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,',
        src: '/assets/portraits/business/18.webp',
        alt: 'person4',
        tel: '+420777111222', 
    },
    {
        name: "Olga Kaslová",
        likes: '158',
        reviews: '18',
        moto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,',
        src: "/assets/portraits/business/15.webp",
        alt: 'person4',
        tel: '+420777111222',
    },
    {
        name: "Lukáš Vituj",
        likes: '158',
        reviews: '18',
        moto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,',
        src: "/assets/portraits/business/18.webp",
        alt: 'person4',
        tel: '+420777111222', 
    },
    {
        name:  "Jane Doe",
        likes: '158',
        reviews: '18',
        moto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,',
        src: "/assets/portraits/business/9.webp",
        alt: 'person4',
        tel: '+420777111222', 
    },
    {
        name:  "Layla Doe",
        likes: '158',
        reviews: '18',
        moto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,',
        src: "/assets/portraits/business/2.webp",
        alt: 'person4',
        tel: '+420777111222', 
    }
]

export const TestPeople = [
    {
        name: "John Doe",
        number: '01',
        moto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        src: "/svg/tree.webp",
        alt: "profile_pic1",
        photo1: '/assets/reviewsBackground.webp',
        altText1: 'asset1',
        photo2: '/assets/reviewsBackground.webp',
        altText2: 'asset2',
    },
    {
        name: "Jane Doe",
        number: '02',
        moto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        src: "/svg/cactus.webp",
        alt: "profile_pic1",
        photo1: '/assets/reviewsBackground.webp',
        altText1: 'asset1',
        photo2: '/assets/reviewsBackground.webp',
        altText2: 'asset2',
    },
    {
        name: "Jane Doe",
        number: '03',
        moto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        src: "/svg/house.webp",
        alt: "profile_pic1",
        photo1: '/assets/reviewsBackground.webp',
        altText1: 'asset1',
        photo2: '/assets/reviewsBackground.webp',
        altText2: 'asset2',
    },
    {
        name: "Jane Doe",
        number: '04',
        moto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            src: "/svg/tree.webp",
        alt: "profile_pic1",
        photo1: '/assets/reviewsBackground.webp',
        altText1: 'asset1',
        photo2: '/assets/reviewsBackground.webp',
        altText2: 'asset2',
    },
    {
        name: "Jane Doe",
        number: '05',
        moto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        src: "/svg/rock.webp",
        alt: "profile_pic1",
        photo1: '/assets/reviewsBackground.webp',
        altText1: 'asset1',
        photo2: '/assets/reviewsBackground.webp',
        altText2: 'asset2',
    },
    {
        name: "Jane Doe",
        number: '06',
        moto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        src: "/svg/tree2.webp",
        alt: "profile_pic1",
        photo1: '/assets/reviewsBackground.webp',
        altText1: 'asset1',
        photo2: '/assets/reviewsBackground.webp',
        altText2: 'asset2',
    },
    {
        name: "Jane Doe",
        number: '07',
        moto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        src: "/svg/water.webp",
        alt: "profile_pic1",
        photo1: '/assets/reviewsBackground.webp',
        altText1: 'asset1',
        photo2: '/assets/reviewsBackground.webp',
        altText2: 'asset2',
    },
    {
        name: "Jane Doe",
        number: '08',
        moto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        src: "/svg/tree.webp",
        alt: "profile_pic1",
        photo1: '/assets/reviewsBackground.webp',
        altText1: 'asset1',
        photo2: '/assets/reviewsBackground.webp',
        altText2: 'asset2',
    },
]